# Generated by Django 5.1.6 on 2025-02-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('identifier', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('aurora', 'Aurora'), ('digitization', 'Digitization'), ('legacy_digital', 'Legacy Born Digital'), ('av_digitization', 'AV Digitization')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('identifiers', models.JSONField(blank=True, null=True)),
                ('rights_statements', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('identifier', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')])),
                ('service', models.CharField(choices=[('ursa_major', 'Ursa Major'), ('fornax', 'Fornax'), ('webhook', 'Webhook'), ('aquarius', 'Aquarius')])),
                ('message', models.CharField(max_length=255)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('package_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
            ],
        ),
    ]
