# Generated by Django 5.1.6 on 2025-02-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=36)),
                ('origin', models.CharField(choices=[('aurora', 'Aurora'), ('digitization', 'Digitization'), ('legacy_digital', 'Legacy Born Digital'), ('av_digitization', 'AV Digitization')], max_length=20)),
                ('identifiers', models.JSONField(blank=True, null=True)),
                ('aurora_accession_identifier', models.JSONField(blank=True, null=True)),
                ('rights_statements', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=36)),
                ('outcome', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')])),
                ('service', models.CharField(choices=[('ursa_major', 'Ursa Major'), ('fornax', 'Fornax'), ('webhook', 'Webhook'), ('aquarius', 'Aquarius')])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
            ],
        ),
    ]
