# Generated by Django 5.1.6 on 2025-02-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='package',
            new_name='package_identifier',
        ),
    ]
