# Generated by Django 5.1.6 on 2025-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='service',
            field=models.CharField(choices=[('digital_ingest_discovery', 'Discovery'), ('digital_ingest_assembly', 'Assembly'), ('digital_ingest_webhook', 'Webhook'), ('digital_ingest_transformation', 'Transformation')]),
        ),
    ]
