# Generated by Django 5.1.6 on 2025-02-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='archivesspace_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='aurora_accession_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
