# Generated by Django 5.2 on 2025-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='last_outcome',
            field=models.CharField(blank=True, choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], null=True),
        ),
    ]
