# Generated by Django 5.2 on 2025-04-30 14:41

from django.db import migrations


def add_last_outcome(apps, schema_editor):
    Package = apps.get_model("api", "Package")
    for package in Package.objects.all():
        package_events = package.event_set.all()
        if len(package_events):
            last_outcome = package_events.order_by('-last_modified')[0].outcome
            package.last_outcome = last_outcome
            package.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_package_last_outcome'),
    ]

    operations = [
        migrations.RunPython(add_last_outcome),
    ]
