# Generated by Django 5.2 on 2025-06-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250430_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='last_outcome',
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('IN PROCESS', 'In Process'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='IN PROCESS'),
        ),
    ]
