# Generated by Django 5.2 on 2025-06-23 20:24

from django.db import migrations


def migrate_status(apps, schema_editor):
    Package = apps.get_model("api", "Package")
    for package in Package.objects.all():
        if package.status == 'FAILURE':
            package.status == 'ERROR'
        if package.status == 'SUCCESS':
            package.status = 'COMPLETE'
        else:
            package.status = 'IN PROGRESS'
        package.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_package_last_outcome_package_status'),
    ]

    operations = [
        migrations.RunPython(migrate_status),
    ]
