# Generated by Django 5.2.3 on 2025-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_package_created_alter_package_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
