# Generated by Django 5.2.9 on 2026-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_package_created_alter_package_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='service',
            field=models.CharField(choices=[('digital_ingest_discovery', 'Discovery'), ('digital_ingest_assembly', 'Assembly'), ('digital_ingest_webhook', 'Webhook'), ('digital_ingest_transformation', 'Transformation'), ('iiif_derivatives', 'IIIF Derivatives'), ('iiif_manifests', 'IIIF Manifests')]),
        ),
    ]
