# Generated by Django 5.2.12 on 2026-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_event_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
