name: Deploy

on:
  push:
    branches:
    #   - base
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    env:
      APPLICATION_NAME: zodiac_backend
      APPLICATION_PORT: 80
      AWS_BUCKET_NAME: "${{ github.ref_name == 'development' && 'rac-dev-deploy' || 'rac-prod-deploy' }}"
      DEPLOY_ZIP_DIR: "${{ github.ref_name == 'development' && 'build-dev' || 'build-prod' }}"
      DEPLOY_ZIP_NAME: zodiac_backend.zip
      DEPLOYMENT_GROUP: # TODO

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Export secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Clone deploy scripts if not present
        run: git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git;

      - name: Substitute environment variables
        uses: tvarohohlavy/inplace-envsubst-action@v1.0.0
        with:
          files: |
            $APPLICATION_NAME/config.py.deploy
            appspec.yml.deploy
            deploy_scripts/curl_index.sh.deploy
            deploy_scripts/install_dependencies_django.sh.deploy
            deploy_scripts/run_management_commands_django.sh.deploy
            deploy_scripts/set_permissions.sh.deploy

      - name: Rename deploy files
        run: |
          mv ${{ env.APPLICATION_NAME }}/config.py.deploy ${{ env.APPLICATION_NAME }}/config.py
          mv appspec.yml.deploy appspec.yml
          mv deploy_scripts/curl_index.sh.deploy deploy_scripts/curl_index.sh
          mv deploy_scripts/install_dependencies_django.sh.deploy deploy_scripts/install_dependencies_django.sh
          mv deploy_scripts/run_management_commands_django.sh.deploy deploy_scripts/run_management_commands_django.sh
          mv deploy_scripts/set_permissions.sh.deploy deploy_scripts/set_permissions.sh

      - name: Make deploy scripts executable
        run: chmod +x deploy_scripts/*.sh

      - name: Create deployment zip
        run: sudo deploy_scripts/make_zip_django.sh ${{ env.DEPLOY_ZIP_DIR }} ${{ env.DEPLOY_ZIP_NAME}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 cp $DEPLOY_ZIP_DIR s3://${{ env.AWS_BUCKET_NAME }} --recursive

      - name: Deploy to AWS CodeDeploy
        run: aws deploy create-deployment
          --region ${{ secrets.AWS_REGION }}
          --application-name ${{ env.APPLICATION_NAME }}
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP }}
          --s3-location bucket=${{ env.AWS_BUCKET_NAME }},bundleType=zip,key=${{ env.DEPLOY_ZIP_NAME }}
